### PR TITLE
Prepare a micro lwt-ish set of functions for NodeJS

### PR DESCRIPTION
**Pull request by foretspaisibles**
**This is work in progress, please do not merge! This branch is also likely to be rebased.**

So I finally found some tome to get this started, there is a lot of things to be done before merging, but maybe you already have some comments of any kind?  Also, I am not familiar with oasis, can you recommend a document to get started as quickly as possible?

### CODE REVIEW

**Comment by fxfactorial** [comment]
Okay great!, a few things. 
1. I think it would be better to make a sub package and call it `lwt`, so that we could do: `nodejs.lwt`, an example on how to do it with oasis: https://github.com/bean-code/ocaml-npm-express/blob/master/_oasis#L27
2. Why don't we separate out the JS utilities out to a separate library?
3. And yea, we can add an Lwt layer on top of the nodejs code...although I'm a little worried if getting the semantics right will work, since nodejs is already itself async

**Comment by foretspaisibles** [comment]
> Why don't we separate out the JS utilities out to a separate library?

I think I _almost_ got this right, but reinstalling fails: ocamlfind complains that the pervasives_js META file already exists.

**Comment by fxfactorial** [comment]
Awesome! Will look at it tonight and fix if anything wrong.

**Comment by foretspaisibles** [comment]
BTW This is still WIP I hope I can add a few actually useful functions to this PR within the next days. :)

**Pull request closed without merging**
